### ISSUE TITLE
unexpected results from ipl-modeling tests

### ISSUE THREAD

**Issue by juniorprincewang** [fdu-sec/NestFuzz#6]
I compiled `ipl-modeling/test/loopTest.c` with `test-clang loopTest.c -o loopTestNew`. However the executing result of `loopTestNew` is not the same as `loopTest`. Can someone help to explain it?

      0123456789
      fp_label: 0
      []
      buffer_label: 0
      []
      dst_label: 0
      []
      34 
      buffer_label: 0
      []
      dst_label: 0
      []
      buffer_label: 0
      []
      dst_label: 0
      []
      buffer_label: 0
      []
      dst_label: 0
      []

**Comment by fdu-sec** [comment]
The following steps may fix this issue:

1. Modify  Line 48 in `loopTest.c`
```
-       fp = fopen("file", "rb");
+       fp = fopen("file.isi", "rb");
```
2. Create a new file with `.isi `extension:
```
cp file file.isi
```
3. Recompile loopTest.c
```
test-clang loopTest.c -o loopTestNew
```

The issue arises because NestFuzz only performs taint analysis for inputs with the `.isi` extension in their filenames.
